//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageEntity
    {
        public long imageId { get; set; }
        public string title { get; set; }
        public System.DateTime fechaSubida { get; set; }
        public string aperture { get; set; }
        public string exposureTime { get; set; }
        public string iso { get; set; }
        public string whiteBalance { get; set; }
        public long author { get; set; }
        public long categoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
