//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.ImageEntity = new HashSet<ImageEntity>();
        }
    
        public long tagId { get; set; }
        public string tagName { get; set; }
        public long taggedImagesNumber { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): ImageTag
        /// </summary>
        public virtual ICollection<ImageEntity> ImageEntity { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + (tagName == null ? 0 : tagName.GetHashCode());
    			hash = hash * multiplier + taggedImagesNumber.GetHashCode();
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type? 
    
            Tag target = obj as Tag;
    
    		return true
               &&  (this.tagId == target.tagId )       
               &&  (this.tagName == target.tagName )       
               &&  (this.taggedImagesNumber == target.taggedImagesNumber )       
               ;
    
        }
    
    
    	public static bool operator ==(Tag  objA, Tag  objB)
        {
            // Check if the objets are the same Tag entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Tag  objA, Tag  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strTag = new StringBuilder();
    
    		strTag.Append("[ ");
           strTag.Append(" tagId = " + tagId + " | " );       
           strTag.Append(" tagName = " + tagName + " | " );       
           strTag.Append(" taggedImagesNumber = " + taggedImagesNumber + " | " );       
            strTag.Append("] ");    
    
    		return strTag.ToString();
        }
    
    
    }
}
